#15/UI/BlueLabel
CC2021-WBL/GOOD-BOI-Application pull request #31
Opened 2022-01-12 19:41 UTC by KatarzynaChmielecka

![image](https://user-images.githubusercontent.com/56206231/150021372-b7e57c14-02d8-47dd-9551-9a46ffb63b64.png)

2022-01-17 18:04 UTC, MonikaKrella requested changes

2022-01-17 18:04 UTC, MonikaKrella commented on src/Atoms/GreyLabel/GreyLabel.js
> +  text: PropTypes.string,
shouldn't be text as required prop?

2022-01-17 23:57 UTC, Smyku6 requested changes

2022-01-17 23:57 UTC, Smyku6 commented on src/Atoms/GreyLabel/GreyLabel.js
> +const GreyLabel = (props) => {
exactly `const GreyLabel = ( { text } ) => {`

2022-01-17 23:57 UTC, Smyku6 commented on src/Atoms/GreyLabel/GreyLabel.js
> +      <p className="greyLabelText">{props.text}</p>
so if You destructure You can use here `{text}`

2022-01-17 23:57 UTC, Smyku6 commented on src/Atoms/GreyLabel/GreyLabelStyled.js
> +const GreyLabelContainer = styled.div`
change name of this Component to the same as filename - `GreyLabelStyled`

2022-01-17 23:57 UTC, Smyku6 commented on src/Atoms/GreyLabel/GreyLabelStyled.js
> +  font-family: Mulish;
You can erase this line - we had this in our index.css at this moment 
`* {
  font-family: 'Mulish', sans-serif
}`

2022-01-18 22:45 UTC, Smyku6 approved these changes
Good GreyLabel Kasia!
![image](https://user-images.githubusercontent.com/75560322/150030803-8c8c2e00-a918-4bbd-a705-29808f1fc916.png)

2022-01-18 22:45 UTC, merged