#18/UI/NavElement
CC2021-WBL/GOOD-BOI-Application pull request #35
Opened 2022-01-13 02:26 UTC by KatarzynaChmielecka

![image](https://user-images.githubusercontent.com/56206231/150026114-ef58fd41-1781-4a4d-8b66-5e430d8d32ab.png)

2022-01-16 11:23 UTC, Smyku6 commented on src/Organisms/NavElement/NavElementStyled.js
> +export const NavElementContainer = styled.div`
change name to the same as filename - NavElementStyled

2022-01-16 11:24 UTC, Smyku6 commented on src/Organisms/NavElement/NavElementStyled.js
> +export const Logo = styled.div`
move this component (Logo) to Atoms

2022-01-16 11:25 UTC, Smyku6 commented on src/Organisms/NavElement/NavElementStyled.js
> +export const LinkWrapper = styled.div`
move this component (LinkWrapper) to Atoms

2022-01-16 11:32 UTC, Smyku6 commented on src/Organisms/NavElement/NavElementStyled.js
> +
add 
border: solid 1px ${COLORS.grey400};

2022-01-16 11:55 UTC, Smyku6 commented on src/Organisms/NavElement/NavElementStyled.js
> +    font-size: 14px;
remember- fight with REM (relative to font-size of the root element)

2022-01-16 11:56 UTC, Smyku6 commented on src/Organisms/NavElement/NavElementStyled.js
> +  margin: 0;
think about left and right margin of your container (I propose 1REM on the left and 1REM on the right)

2022-01-16 11:59 UTC, n0macx reviewed
Maybe You should add NavElement with proper text to every view not only home page ?

2022-01-16 12:11 UTC, Smyku6 requested changes
in comments

2022-01-16 13:43 UTC, KatarzynaChmielecka commented
> Maybe there a way for the text od nav to change after changing views ?

What do you mean?

2022-01-18 22:52 UTC, Smyku6 submitted a review, later dismissed

2022-01-19 15:50 UTC, closed without merging